version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - chat-network
volumes:
  mongo-data:
networks:
  chat-network:
